In [2]:
import numpy as np

from gymnasium import utils
from gymnasium.envs.mujoco import MujocoEnv
from gymnasium.error import Error
from gymnasium.spaces import Box
from gymnasium.utils.env_checker import check_env

In [3]:
class QRPfRA_v3(MujocoEnv, utils.EzPickle):
    metadata = {
        "render_modes": [
            "human",
            "rgb_array",
            "depth_array",
        ],
    }

    def __init__(self, xml_file="/Users/deniz/PycharmProjects/QRPfRA_Senior_Project/QRPfRA/IK_Models/qrpfra_v3_leg_ik_scene_right.xml", frame_skip=1, **kwargs):
        utils.EzPickle.__init__(self, xml_file, frame_skip, **kwargs)

        MujocoEnv.__init__(
            self,
            xml_file,
            frame_skip=frame_skip,
            observation_space=None,  # needs to be defined after
            default_camera_config={},
            **kwargs,
        )

        self.metadata = {
            "render_modes": [
                "human",
                "rgb_array",
                "depth_array",
            ],
            "render_fps": int(np.round(1.0 / self.dt)),
        }

        obs_size = self.data.qpos.size + self.data.qvel.size

        self.observation_space = Box(
            low=-np.inf, high=np.inf, shape=(obs_size,), dtype=np.float64
        )

    def step(self, action):

        self.do_simulation(action, self.frame_skip)

        observation = self._get_obs()
        reward = 0
        info = {}

        if self.render_mode == "human":
            self.render()

        return observation, reward, False, False, info

    def _get_obs(self):
        sensor_data = self.data.sensordata.flat.copy()

        return sensor_data

    def reset_model(self):
        qpos = self.init_qpos
        qvel = self.init_qvel
        self.set_state(qpos, qvel)

        observation = self._get_obs()

        return observation

    def _get_reset_info(self):
        return {"works": True}



In [6]:
env = QRPfRA_v3()
check_env(env)
obs = env.reset()
print(obs)


(array([ 0.046 ,  0.1435, -0.1245,  0.    ,  0.    ,  0.    ]), {'works': True})


/Users/deniz/miniconda3/envs/QRPfRA_Senior_Project/lib/python3.11/site-packages/gymnasium/utils/env_checker.py:247: UserWarning: WARN: For Box action spaces, we recommend using a symmetric and normalized space (range=[-1, 1] or [0, 1]). See https://stable-baselines3.readthedocs.io/en/master/guide/rl_tips.html for more information.
  logger.warn(
/Users/deniz/miniconda3/envs/QRPfRA_Senior_Project/lib/python3.11/site-packages/gymnasium/utils/env_checker.py:225: UserWarning: WARN: A Box observation space minimum value is -infinity. This is probably too low.
  logger.warn(
/Users/deniz/miniconda3/envs/QRPfRA_Senior_Project/lib/python3.11/site-packages/gymnasium/utils/env_checker.py:229: UserWarning: WARN: A Box observation space maximum value is -infinity. This is probably too high.
  logger.warn(
/Users/deniz/miniconda3/envs/QRPfRA_Senior_Project/lib/python3.11/site-packages/gymnasium/utils/env_checker.py:321: UserWarning: WARN: Not able to test alternative render modes due to the environ

In [7]:
leg_dataset = [] # [obs0, obs1, obs2, act0, act1, act2]

In [8]:
for i in range(-100, 101, 4):
    for j in range(-100, 101, 4):
        for k in range(-100, 101, 4):
            #env.render_mode = "human"
            env_obs = []
            for step_cnt in range(0,3):
                obs, reward, done, _, info = env.step([float(m) for m in [i, j, k]])
                if step_cnt == 2:
                    env_obs = obs
            

            leg_dataset.append([env_obs[0], env_obs[1], env_obs[2], i/100, j/100, k/100])


env.close()

In [9]:
print(len(leg_dataset))

132651


In [10]:

# Save the leg_dataset variable to a text file with comma separation
np.savetxt('leg_dataset.txt', leg_dataset, delimiter=',')


In [11]:
#Convert left leg list to numpy array
leg_dataset_as_np = np.array(leg_dataset)

In [21]:
print(leg_dataset_as_np[0:4])

observations = (leg_dataset_as_np[:, 0:3][:] + 1)
print(observations)
actions = leg_dataset_as_np[:, 3:][:]
print(actions)

[[ 0.16802824 -0.17832992 -0.02959151 -1.         -1.         -1.        ]
 [ 0.18593527 -0.15028785 -0.05653176 -1.         -1.         -0.96      ]
 [ 0.18776632 -0.1465833  -0.05628311 -1.         -1.         -0.92      ]
 [ 0.190028   -0.14132874 -0.05799825 -1.         -1.         -0.88      ]]
[[1.16802824 0.82167008 0.97040849]
 [1.18593527 0.84971215 0.94346824]
 [1.18776632 0.8534167  0.94371689]
 ...
 [1.08074731 1.04767694 0.99132841]
 [1.07875458 1.04270491 0.99018395]
 [1.07659415 1.03785968 0.98894317]]
[[-1.   -1.   -1.  ]
 [-1.   -1.   -0.96]
 [-1.   -1.   -0.92]
 ...
 [ 1.    1.    0.92]
 [ 1.    1.    0.96]
 [ 1.    1.    1.  ]]


In [24]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
import datetime
from tensorflow.keras import layers, models


# Split the dataset into training and testing sets
train_obs, test_obs, train_actions, test_actions = train_test_split(observations, actions, test_size=0.1, shuffle=True)

# Define the model architecture

ik_input = tf.keras.Input(shape=(3,))
x = layers.Dense(128, activation="relu")(ik_input)
x = layers.Dense(128, activation="relu", kernel_regularizer=tf.keras.regularizers.l2())(x)
x = layers.Dense(128, activation="relu", kernel_regularizer=tf.keras.regularizers.l2())(x)

ik_output = layers.Dense(3, activation="tanh")(x)


model = models.Model(ik_input, ik_output)
# Compile the model
optimizer = tf.keras.optimizers.legacy.Adam(learning_rate=0.0001)  # Set the learning rate here
model.compile(optimizer=optimizer, loss=tf.keras.losses.Huber(), metrics=['accuracy'])

# Train the model
model.fit(observations, actions, epochs=10, batch_size=2)

# Evaluate the model on the testing set
test_loss = model.evaluate(test_obs, test_actions)
print('Test Loss:', test_loss)
current_time = datetime.datetime.now()
print("Current Time:", current_time)


Epoch 1/10
66326/66326 [==============================] - 79s 1ms/step - loss: 0.1532 - accuracy: 0.5384
Epoch 2/10
66326/66326 [==============================] - 79s 1ms/step - loss: 0.0983 - accuracy: 0.6474
Epoch 3/10
66326/66326 [==============================] - 72s 1ms/step - loss: 0.0855 - accuracy: 0.7195
Epoch 4/10
66326/66326 [==============================] - 82s 1ms/step - loss: 0.0641 - accuracy: 0.8046
Epoch 5/10
66326/66326 [==============================] - 82s 1ms/step - loss: 0.0523 - accuracy: 0.8441
Epoch 6/10
66326/66326 [==============================] - 86s 1ms/step - loss: 0.0459 - accuracy: 0.8642
Epoch 7/10
66326/66326 [==============================] - 87s 1ms/step - loss: 0.0418 - accuracy: 0.8718
Epoch 8/10
66326/66326 [==============================] - 84s 1ms/step - loss: 0.0390 - accuracy: 0.8777
Epoch 9/10
66326/66326 [==============================] - 86s 1ms/step - loss: 0.0367 - accuracy: 0.8814
Epoch 10/10
415/415 [==============================] - 

In [25]:
model.save("right_legs_model_plus50", overwrite=True)

INFO:tensorflow:Assets written to: right_legs_model_plus50/assets


INFO:tensorflow:Assets written to: right_legs_model_plus50/assets
